"""initial migration

Revision ID: 99fd6016d5d5
Revises: 70a32af1b59e
Create Date: 2024-07-30 16:49:52.312628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fd6016d5d5'
down_revision = '70a32af1b59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_quests_player_id_players')),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_player_quests_quest_id_quests')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_quests')
    op.drop_table('quests')
    op.drop_table('players')
    # ### end Alembic commands ###
